---
- name: "[ homebrew] Configure Homebrew taps"
  homebrew_tap:
    name: "{{ item }}"
  become: true
  loop: "{{ brew_taps }}"

- name: "[ homebrew] Install Homebrew formulae"
  homebrew:
    name: "{{ item }}"
  become: true
  loop: "{{ brew_packages }}"

- name: "[ homebrew] Install Homebrew casks"
  homebrew_cask:
    name: "{{ item }}"
  become: true
  loop: "{{ cask_packages }}"