#!/bin/bash

set -e

PYTHON_USER_BIN=$(python3 -m site --user-base)/bin

PATH="/opt/Homebrew/bin:$PYTHON_USER_BIN:$PATH"
ansible-playbook -i ansible/inventory/hosts ansible/playbooks/macos.yml 

# if [[ "$(uname)" == "Darwin" ]]; then
  # PATH="/opt/Homebrew/bin:$PYTHON_USER_BIN:$PATH"
  # ansible-playbook ./ansible/playbooks/macos.yml  
# else
#   PATH="$PYTHON_USER_BIN:$PATH"
#   ansible-playbook ./ansible/playbooks/linux.yml
