- hosts: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: "[﬒ dotfiles] Include config.yml overrides"
      include_vars: "{{ item }}"
      with_fileglob: "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ["brew"]
